### PR TITLE
FEATURE: Support Neos 3.x & Elasticsearch

### PR DESCRIPTION
**Pull request by kdambekalns**
This provides compatibility with Neos 3.x and allows to use Elasticsearch
to collect the news to be displayed.

Elasticsearch can be used by configuring the plugin as explained in the
documentation, depending on the amount of news this can provide a
great improvement in rendering speed.

Thanks to bellicon and Peter Bucher for help and sponsoring.

### CODE REVIEW

**Comment by kdambekalns** [comment]
If this is merged, #9 can be closed as well.

**Comment by pankajlele** [comment]
@kdambekalns Thank you all for your contribution. Will go ahead and tag it. What tag / version do you recommend? 3.3.0 looks fine?

**Comment by kdambekalns** [comment]
Well, there only exist 1.0.0-alpha1 and 1.0.2 so far, so a 2.0.0 would be fine. But since there are branches working with Neos 2.x, I'd **go for 3.0.0**. It is correct in terms of semantics and signals "I work with Neos 3.x".

And while you are at it, you could merge #11 and then tag 2.0.0 from the 2.3 branch…

**Comment by pankajlele** [comment]
Thanks for your suggestion. Done!

**Comment by kdambekalns** [comment]
🚀

**Comment by pankajlele** [comment]
Packagist is little unhappy. Fixing...

> Skipped branch 2.3, Invalid package information: 
> License "GPL-3.0+" is a deprecated SPDX license identifier, use "GPL-3.0-or-later" instead

**Comment by pankajlele** [comment]
@kdambekalns I am facing some errors through Fluid templates. I will fix and commit. But just wondering if its the same case with you?

**Comment by kdambekalns** [comment]
@pankajlele What errors do you get?

**Pull request merged**
